/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    App: typeof import('./src/App.vue')['default']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATypography: typeof import('ant-design-vue/es')['Typography']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    ComponentsHelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    copy: typeof import('./src/login/views/ForgetPasswordView copy.vue')['default']
    GallerieComponentsDialogImageUpdate: typeof import('./src/gallerie/components/DialogImageUpdate.vue')['default']
    GallerieComponentsDialogueImageUpdate: typeof import('./src/gallerie/components/DialogueImageUpdate.vue')['default']
    GallerieViewsGallerieViews: typeof import('./src/gallerie/views/gallerieViews.vue')['default']
    HomeViewsHomeViews: typeof import('./src/home/views/HomeViews.vue')['default']
    LoginViewsForgetPasswordView: typeof import('./src/login/views/ForgetPasswordView.vue')['default']
    LoginViewsLoginView: typeof import('./src/login/views/LoginView.vue')['default']
    LoginViewsRegisterView: typeof import('./src/login/views/RegisterView.vue')['default']
    LoginViewsResetPasswordView: typeof import('./src/login/views/ResetPasswordView.vue')['default']
    OnbordingViewsOnbordingView: typeof import('./src/onbording/views/onbordingView.vue')['default']
    ParameterViewsAccountView: typeof import('./src/parameter/views/AccountView.vue')['default']
    ParameterViewsCheckCodeView: typeof import('./src/parameter/views/CheckCodeView.vue')['default']
    RolesViewsCreateRightView: typeof import('./src/roles/views/CreateRightView.vue')['default']
    RolesViewsCreateRoleView: typeof import('./src/roles/views/CreateRoleView.vue')['default']
    RolesViewsRolesView: typeof import('./src/roles/views/RolesView.vue')['default']
    RolesViewsUpdateRoleView: typeof import('./src/roles/views/UpdateRoleView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
